Repository TeamAraBook/AraBook-iOS, pull requests merged in 2024-10, with the labels that each got.

#9 [Feat] #7 - 기록하기 상세뷰 구현
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Resource/Colors.xcassets/Gray400.colorset/Contents.json
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailBackView.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailFrontView.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailModel.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailViewController.swift
  AraBook/AraBook/Presentation/Record/RecordsList/Cells/RecordListCell.swift
  AraBook/AraBook/Presentation/Record/RecordsList/Model/RecordListModel.swift
  AraBook/AraBook/Presentation/Record/RecordsList/ViewControllers/RecordListViewController.swift
  AraBook/AraBook/Presentation/Record/RecordsList/ViewModel/RecordListViewModel.swift
  AraBook/AraBook/Presentation/Record/RecordsList/Views/RecordListView.swift
  AraBook/AraBook/Presentation/RecordsList/Model/RecordListModel.swift
Labels: 🌱 Feat, 🐰 아라

#11 #10 feat: 검색뷰 ui 구현 및 api 연결
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Extension/UIImageView+.swift
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_close.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_close.imageset/ic_close.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_search.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_search.imageset/ic_search_2_line.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_search_green.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_search_green.imageset/ic_search_2_line.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_empty.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_empty.imageset/Group 31.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_empty.imageset/Group 31@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_empty.imageset/Group 31@3x.png
  AraBook/AraBook/Global/Resource/Colors.xcassets/Gray800.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Colors.xcassets/Gray900.colorset/Contents.json
  AraBook/AraBook/Info.plist
  AraBook/AraBook/Network/Base/BaseTargetType.swift
  AraBook/AraBook/Network/Base/GeneralResponse.swift
  AraBook/AraBook/Network/Base/HeaderConstant.swift
  AraBook/AraBook/Network/Base/NetworkLoggerPlugin.swift
  AraBook/AraBook/Network/Base/URLConstant.swift
  AraBook/AraBook/Network/Data/Home/RecommendAiResponseDto.swift
  AraBook/AraBook/Network/Data/Home/RecommendBestSellerResponseDto.swift
  AraBook/AraBook/Network/Data/Home/SearchBookResponseDto.swift
  AraBook/AraBook/Network/Service/HomeService.swift
  AraBook/AraBook/Network/Target/HomeTarget.swift
  AraBook/AraBook/Presentation/Home/BestSellerModel.swift
  AraBook/AraBook/Presentation/Home/HomeViewModel.swift
  AraBook/AraBook/Presentation/Home/Main/BookCollectionViewCell.swift
  AraBook/AraBook/Presentation/Home/Main/HomeTodayBookView.swift
  AraBook/AraBook/Presentation/Home/Main/HomeViewController.swift
  AraBook/AraBook/Presentation/Home/Main/HomeViewModel.swift
  AraBook/AraBook/Presentation/Home/Search/RecentCollectionViewCell.swift
  AraBook/AraBook/Presentation/Home/Search/SearchTextField/BaseTextField.swift
  AraBook/AraBook/Presentation/Home/Search/SearchTextField/SearchTextField.swift
  AraBook/AraBook/Presentation/Home/Search/SearchViewModel.swift
  AraBook/AraBook/Presentation/Home/Search/SerachViewController.swift
  AraBook/AraBook/Presentation/Home/Search/View/RecentSearchView.swift
  AraBook/AraBook/Presentation/Home/Search/View/SearchResultView.swift
  AraBook/AraBook/Presentation/Home/TodayBookModel.swift
Labels: 🌱 Feat, 🐰 아라

#14 [Feat] #13 - 최근검색어 로컬DB 로직 구현
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_close.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_close.imageset/exit.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_close.imageset/ic_close.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_search.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_search.imageset/img_search.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_search.imageset/img_search@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_search.imageset/img_search@3x.png
  AraBook/AraBook/Presentation/Home/Main/HomeTodayBookView.swift
  AraBook/AraBook/Presentation/Home/Main/HomeViewController.swift
  AraBook/AraBook/Presentation/Home/Search/LocalDBService.swift
  AraBook/AraBook/Presentation/Home/Search/RecentCollectionViewCell.swift
  AraBook/AraBook/Presentation/Home/Search/SearchTextField/SearchTextField.swift
  AraBook/AraBook/Presentation/Home/Search/SearchViewModel.swift
  AraBook/AraBook/Presentation/Home/Search/SerachViewController.swift
  AraBook/AraBook/Presentation/Home/Search/View/RecentSearchView.swift
Labels: 🌱 Feat, 🐰 아라

#17 [Feat] #16 - 책 상세보기 뷰 UI 구현
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Extension/UIImageView+.swift
  AraBook/AraBook/Presentation/BookDetail/BookDetailView.swift
  AraBook/AraBook/Presentation/BookDetail/BookDetailViewController.swift
  AraBook/AraBook/Presentation/BookDetail/BookDetailViewModel.swift
  AraBook/AraBook/Presentation/BookDetail/Views/BookDetailCoverView.swift
  AraBook/AraBook/Presentation/BookDetail/Views/BookDetailDescriptionView.swift
Labels: 🌱 Feat, 🐸 정

#20 [Feat] #15 - 카카오로그인 및 마이페이지 구현
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Application/AppDelegate.swift
  AraBook/AraBook/Application/SceneDelegate.swift
  AraBook/AraBook/Application/User/UserDefaultWrapper.swift
  AraBook/AraBook/Application/User/UserManager.swift
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/btn_kakao.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/btn_kakao.imageset/btn_kakao.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/btn_kakao.imageset/btn_kakao@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/btn_kakao.imageset/btn_kakao@3x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/img_background.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/img_background.imageset/img_background.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/img_background.imageset/img_background@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/img_background.imageset/img_background@3x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/img_logo.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/img_logo.imageset/img_logo.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/img_logo.imageset/img_logo@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Onboarding/img_logo.imageset/img_logo@3x.png
  AraBook/AraBook/Network/Base/HeaderConstant.swift
  AraBook/AraBook/Network/Base/URLConstant.swift
  AraBook/AraBook/Network/Data/Auth/LoginRequestDto.swift
  AraBook/AraBook/Network/Data/Auth/LoginResponseDto.swift
  AraBook/AraBook/Network/Service/AuthService.swift
  AraBook/AraBook/Network/Target/AuthTarget.swift
  AraBook/AraBook/Presentation/Common/TabBar/TabBarController.swift
  AraBook/AraBook/Presentation/Mypage/MypageTableViewCell.swift
  AraBook/AraBook/Presentation/Mypage/MypageViewController.swift
  AraBook/AraBook/Presentation/Mypage/SettingMenu.swift
  AraBook/AraBook/Presentation/Onboarding/Login/LoginViewController.swift
  AraBook/AraBook/Presentation/Onboarding/Login/LoginViewModel.swift
  AraBook/AraBook/Presentation/Onboarding/Splash/SplashViewController.swift
Labels: 🌱 Feat, 🐰 아라

#23 [Fix] #22 - 홈뷰 서버 수정사항 반영
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/_ic_edit.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/_ic_edit.imageset/_ic_edit.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/_ic_edit.imageset/_ic_edit@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/_ic_edit.imageset/_ic_edit@3x.png
  AraBook/AraBook/Network/Data/Home/RecommendAiResponseDto.swift
  AraBook/AraBook/Presentation/Common/NaviBar/CustomNavigationBar.swift
  AraBook/AraBook/Presentation/Home/Main/HomeTodayBookView.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailViewController.swift
Labels: 🎈 Fix, 🐰 아라

#24 [Feature] #21 - 책 기록 뷰 UI 구현 및 api 연결
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Extension/ObservableType+.swift
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedFun.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedFun.imageset/Group 21.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedLifeBook.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedLifeBook.imageset/Group 987824.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedLittleBit.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedLittleBit.imageset/Group 22.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedNormal.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedNormal.imageset/Group 24.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedNotMuch.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/selectedNotMuch.imageset/Group 23.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedFun.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedFun.imageset/Group 987815.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedLifeBook.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedLifeBook.imageset/Group 987819.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedLittleBit.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedLittleBit.imageset/Group 987816.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedNormal.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedNormal.imageset/Group 987818.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedNotMuch.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Character/unSelectedNotMuch.imageset/Group 987817.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/ic_back_white.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/ic_back_white.imageset/ic_left_line_ios.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordBook/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordBook/ic_calendar.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordBook/ic_calendar.imageset/Group.svg
  AraBook/AraBook/Global/Resource/Colors.xcassets/Gray200.colorset/Contents.json
  AraBook/AraBook/Network/Base/Networkable.swift
  AraBook/AraBook/Network/Base/ServiceError.swift
  AraBook/AraBook/Network/Base/URLConstant.swift
  AraBook/AraBook/Network/Service/RecordBookService.swift
  AraBook/AraBook/Presentation/RecordBook/Models/CharacterModel.swift
  AraBook/AraBook/Presentation/RecordBook/RecordBookView.swift
  AraBook/AraBook/Presentation/RecordBook/RecordBookViewController.swift
  AraBook/AraBook/Presentation/RecordBook/RecordBookViewModel.swift
  AraBook/AraBook/Presentation/RecordBook/Views/BookReviewView.swift
  AraBook/AraBook/Presentation/RecordBook/Views/CalendarView.swift
  AraBook/AraBook/Presentation/RecordBook/Views/CharacterView.swift
  AraBook/AraBook/Presentation/RecordBook/Views/CheckButton.swift
  AraBook/AraBook/Presentation/RecordBook/Views/DatePickerViewController.swift
  AraBook/AraBook/Presentation/RecordBook/Views/RecordDateView.swift
Labels: 🌱 Feat, 🐸 정

#29 [Feat] #28 - 기록상세 뷰 api 연결
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Extension/UIColor+.swift
  AraBook/AraBook/Network/Base/URLConstant.swift
  AraBook/AraBook/Network/Service/RecordBookService.swift
  AraBook/AraBook/Network/Target/RecordTarget.swift
  AraBook/AraBook/Presentation/Home/Main/BookCollectionViewCell.swift
  AraBook/AraBook/Presentation/Home/Main/HomeTodayBookView.swift
  AraBook/AraBook/Presentation/Home/Main/HomeViewController.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailBackView.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailFrontView.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailModel.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailResponseDto.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailViewController.swift
  AraBook/AraBook/Presentation/Record/RecordsList/Cells/RecordListCell.swift
  AraBook/AraBook/Presentation/Record/RecordsList/ViewControllers/RecordListViewController.swift
  AraBook/AraBook/Presentation/Record/RecordsList/ViewModel/RecordListViewModel.swift
  AraBook/AraBook/Presentation/RecordBook/RecordBookViewController.swift
Labels: 🌱 Feat, 🐰 아라

#34 [Chore] #33 - 자잘한 수정사항 반영
  AraBook/AraBook/Application/User/UserManager.swift
  AraBook/AraBook/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/AppIcon.appiconset/_logo.png
  AraBook/AraBook/Presentation/BookDetail/BookDetailViewController.swift
  AraBook/AraBook/Presentation/BookDetail/Views/BookDetailCoverView.swift
  AraBook/AraBook/Presentation/BookDetail/Views/BookDetailDescriptionView.swift
  AraBook/AraBook/Presentation/Common/NaviBar/CustomNavigationBar.swift
  AraBook/AraBook/Presentation/Common/Onboarding/ViewControllers/FirstOnboardingViewController.swift
  AraBook/AraBook/Presentation/Common/Onboarding/ViewControllers/ThirdOnboardingViewController.swift
  AraBook/AraBook/Presentation/Common/Onboarding/ViewModel/OnboardingViewModel.swift
  AraBook/AraBook/Presentation/Home/Main/BookCollectionViewCell.swift
  AraBook/AraBook/Presentation/Home/Main/HomeViewController.swift
  AraBook/AraBook/Presentation/Home/Search/SerachViewController.swift
  AraBook/AraBook/Presentation/Onboarding/Login/LoginViewController.swift
  AraBook/AraBook/Presentation/Onboarding/Splash/SplashViewController.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailViewController.swift
  AraBook/AraBook/Presentation/Record/RecordsList/Cells/RecordListCell.swift
  AraBook/AraBook/Presentation/RecordBook/RecordBookView.swift
  AraBook/AraBook/Presentation/RecordBook/RecordBookViewController.swift
Labels: ☂️ Chore, 🐰 아라

#36 [Feat] #35 - 기록하기 수정/삭제 바텀시트 구현 및 삭제 api 연결
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/btn_more.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/btn_more.imageset/btn_mainmenu_ios.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_grabber.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_grabber.imageset/Grabber.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_grabber.imageset/Grabber@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_grabber.imageset/Grabber@3x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_menu_del.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_menu_del.imageset/bottomsheet_menu_ios-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_menu_del.imageset/bottomsheet_menu_ios@2x-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_menu_del.imageset/bottomsheet_menu_ios@3x-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_menu_edit.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_menu_edit.imageset/bottomsheet_menu_ios.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_menu_edit.imageset/bottomsheet_menu_ios@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/bottomsheet_menu_edit.imageset/bottomsheet_menu_ios@3x.png
  AraBook/AraBook/Network/Data/Record/BookDetailResponseDto.swift
  AraBook/AraBook/Network/Data/Record/BookRecordResponseDto.swift
  AraBook/AraBook/Network/Data/Record/EmptyDataResponse.swift
  AraBook/AraBook/Network/Data/Record/RecordBookRequestDto.swift
  AraBook/AraBook/Network/Data/Record/RecordBookResponseDto.swift
  AraBook/AraBook/Network/Service/RecordBookService.swift
  AraBook/AraBook/Network/Service/RecordService.swift
  AraBook/AraBook/Network/Target/RecordTarget.swift
  AraBook/AraBook/Presentation/Common/NaviBar/CustomNavigationBar.swift
  AraBook/AraBook/Presentation/Home/BookDetail/BookDetailView.swift
  AraBook/AraBook/Presentation/Home/BookDetail/BookDetailViewController.swift
  AraBook/AraBook/Presentation/Home/BookDetail/BookDetailViewModel.swift
  AraBook/AraBook/Presentation/Home/BookDetail/Views/BookDetailCoverView.swift
  AraBook/AraBook/Presentation/Home/BookDetail/Views/BookDetailDescriptionView.swift
  AraBook/AraBook/Presentation/Home/Main/BookCollectionViewCell.swift
  AraBook/AraBook/Presentation/Home/Main/HomeViewController.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/Models/OnboardingUserInfo.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/ViewControllers/FirstOnboardingViewController.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/ViewControllers/SecondOnboardingViewController.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/ViewControllers/ThirdOnboardingViewController.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/ViewModel/OnboardingViewModel.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/Views/FirstOnboardingView.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/Views/SecondOnboardingView.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/Views/ThirdOnboardingView.swift
  AraBook/AraBook/Presentation/Onboarding/InputUserInfo/Views/TopicCollectionViewCell.swift
  AraBook/AraBook/Presentation/Onboarding/Login/LoginViewController.swift
  AraBook/AraBook/Presentation/Record/RecordBook/Models/CharacterModel.swift
  AraBook/AraBook/Presentation/Record/RecordBook/RecordBookView.swift
  AraBook/AraBook/Presentation/Record/RecordBook/RecordBookViewController.swift
  AraBook/AraBook/Presentation/Record/RecordBook/RecordBookViewModel.swift
  AraBook/AraBook/Presentation/Record/RecordBook/Views/BookReviewView.swift
  AraBook/AraBook/Presentation/Record/RecordBook/Views/CalendarView.swift
  AraBook/AraBook/Presentation/Record/RecordBook/Views/CharacterView.swift
  AraBook/AraBook/Presentation/Record/RecordBook/Views/CheckButton.swift
  AraBook/AraBook/Presentation/Record/RecordBook/Views/DatePickerViewController.swift
  AraBook/AraBook/Presentation/Record/RecordBook/Views/RecordDateView.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailFrontView.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordDetailViewController.swift
  AraBook/AraBook/Presentation/Record/RecordDetail/RecordEditBSViewController.swift
  AraBook/AraBook/Presentation/Record/RecordsList/ViewControllers/RecordListViewController.swift
  AraBook/AraBook/Presentation/Record/RecordsList/ViewModel/RecordListViewModel.swift
  AraBook/AraBook/Presentation/ViewController.swift
Labels: 🌱 Feat, 🐰 아라
