Repository TeamAraBook/AraBook-iOS, pull requests merged in 2024-09, with the labels that each got.

#2 [Setting] #1 - 프로젝트 세팅
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook.xcodeproj/xcshareddata/xcschemes/AraBook.xcscheme
  AraBook/AraBook/Application/AppDelegate.swift
  AraBook/AraBook/Application/SceneDelegate.swift
  AraBook/AraBook/Base.lproj/Main.storyboard
  AraBook/AraBook/Global/Base.lproj/LaunchScreen.storyboard
  AraBook/AraBook/Global/Extension/UIView+.swift
  AraBook/AraBook/Global/Literals/FontLiterals.swift
  AraBook/AraBook/Global/Literals/SizeLiterals.swift
  AraBook/AraBook/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/ic_back.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/ic_back.imageset/ic_left_line_ios.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/ic_close.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/NaviBar/ic_close.imageset/ic_close.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_home_selected.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_home_selected.imageset/ic_home_fill-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_home_selected.imageset/ic_home_fill@2x-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_home_selected.imageset/ic_home_fill@3x-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_home_unselected.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_home_unselected.imageset/ic_home_fill.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_home_unselected.imageset/ic_home_fill@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_home_unselected.imageset/ic_home_fill@3x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_mypage_selected.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_mypage_selected.imageset/ic_user_filled-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_mypage_selected.imageset/ic_user_filled@2x-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_mypage_selected.imageset/ic_user_filled@3x-1.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_mypage_unselected.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_mypage_unselected.imageset/ic_user_filled.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_mypage_unselected.imageset/ic_user_filled@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_mypage_unselected.imageset/ic_user_filled@3x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_record_selected.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_record_selected.imageset/Group 987832.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_record_selected.imageset/Group 987832@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_record_selected.imageset/Group 987832@3x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_record_unselected.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_record_unselected.imageset/Group 987833.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_record_unselected.imageset/Group 987833@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/TabBar/ic_record_unselected.imageset/Group 987833@3x.png
  AraBook/AraBook/Global/Resource/Colors.xcassets/Contents.json
  AraBook/AraBook/Global/Resource/Colors.xcassets/Gray300.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Colors.xcassets/MainGreen.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Font/Pretendard-Bold.otf
  AraBook/AraBook/Global/Resource/Font/Pretendard-Regular.otf
  AraBook/AraBook/Global/Resource/Font/Pretendard-SemiBold.otf
  AraBook/AraBook/Global/Resource/Font/PyeongChang-Bold.otf
  AraBook/AraBook/Info.plist
  AraBook/AraBook/Network/Base/Config.swift
  AraBook/AraBook/Presentation/Common/NaviBar/CustomNavigationBar.swift
  AraBook/AraBook/Presentation/Common/TabBar/TabBarController.swift
  AraBook/AraBook/Presentation/Common/TabBar/TabBarItem.swift
  AraBook/AraBook/Presentation/ViewController.swift
Labels: ⚙️ Setting, 🐰 아라

#5 [Feat] #3 - 홈화면 ui 구현 및 바인딩
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Extension/NSObject+.swift
  AraBook/AraBook/Global/Extension/UIStackView+.swift
  AraBook/AraBook/Global/Literals/FontLiterals.swift
  AraBook/AraBook/Global/Protocols/ViewModel.swift
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_recommend.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/ic_recommend.imageset/ch_recommend.svg
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_book.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_book.imageset/_img_book.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_book.imageset/_img_book@2x.png
  AraBook/AraBook/Global/Resource/Assets.xcassets/Home/img_book.imageset/_img_book@3x.png
  AraBook/AraBook/Global/Resource/Colors.xcassets/Gray500.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Font/PyeongChang-Regular.otf
  AraBook/AraBook/Info.plist
  AraBook/AraBook/Presentation/Common/TabBar/TabBarController.swift
  AraBook/AraBook/Presentation/Common/TabBar/TabBarItem.swift
  AraBook/AraBook/Presentation/Home/BestSellerModel.swift
  AraBook/AraBook/Presentation/Home/BookCollectionViewCell.swift
  AraBook/AraBook/Presentation/Home/HomeTodayBookView.swift
  AraBook/AraBook/Presentation/Home/HomeViewController.swift
  AraBook/AraBook/Presentation/Home/HomeViewModel.swift
  AraBook/AraBook/Presentation/Home/TodayBookModel.swift
Labels: 🌱 Feat, 🐰 아라

#6 [Feat] #4 - 내 기록 뷰 UI 구현
  AraBook/AraBook.xcodeproj/project.pbxproj
  AraBook/AraBook/Global/Extension/UIView+.swift
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/ic_recordList.imageset/Contents.json
  AraBook/AraBook/Global/Resource/Assets.xcassets/RecordList/ic_recordList.imageset/Frame 58.svg
  AraBook/AraBook/Global/Resource/Colors.xcassets/ChBlue.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Colors.xcassets/ChGreen.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Colors.xcassets/ChOrange.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Colors.xcassets/ChRed.colorset/Contents.json
  AraBook/AraBook/Global/Resource/Colors.xcassets/ChYellow.colorset/Contents.json
  AraBook/AraBook/Presentation/Common/TabBar/TabBarController.swift
  AraBook/AraBook/Presentation/RecordsList/Cells/RecordListCell.swift
  AraBook/AraBook/Presentation/RecordsList/Model/RecordListModel.swift
  AraBook/AraBook/Presentation/RecordsList/ViewControllers/RecordListViewController.swift
  AraBook/AraBook/Presentation/RecordsList/ViewModel/RecordListViewModel.swift
  AraBook/AraBook/Presentation/RecordsList/Views/RecordListView.swift
Labels: 🦋 Design, 🐸 정
